# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
datafile = "city_data.csv"

datafile_df = pd.read_csv(datafile)
datafile_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,pampierstad,-27.78,24.69,29.01,88.0,0.0,8.21,ZA,1.594779e+09
1,jamestown,42.10,-79.24,66.20,72.0,1.0,4.70,US,1.594778e+09
2,kapaa,22.08,-159.32,82.99,74.0,75.0,14.99,US,1.594778e+09
3,vaini,-21.20,-175.20,75.20,73.0,75.0,12.75,TO,1.594778e+09
4,lagoa,39.05,-27.98,68.86,80.0,0.0,6.69,PT,1.594778e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Access maps with unique API key
#gmaps.configure(api_key="AIzaSyCS9o1uaknAsCBpggoeB8HCI0HUeMV8EDE")
gmaps.configure(api_key=g_key)

In [4]:
# Store latitude and longitude in locations
locations = datafile_df[["Lat", "Lng"]]

# Fill NaN values and convert to float
humidity = datafile_df["Humidity"].astype(float)

fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
weather_df = pd.DataFrame(datafile_df, columns=["City", "Country","Max Temp", "Wind Speed", "Cloudiness", "Lat", "Lng"])

weather_df = weather_df.rename(columns={"Max Temp":"MaxTemp", "Wind Speed":"WindSpeed"})

weather_df = weather_df[(weather_df.MaxTemp <= 80) & (weather_df.MaxTemp >= 70) 
                       & (weather_df.WindSpeed >= 10) & (weather_df.Cloudiness == 0)]

weather_df.head(10)

               City Country  MaxTemp  WindSpeed  Cloudiness    Lat     Lng
101          kostek      RU    74.55      10.63         0.0  43.34   46.85
108  guerrero negro      MX    70.92      18.34         0.0  27.98 -114.06
212          darnah      LY    75.09      13.62         0.0  32.77   22.64
434     san quintin      MX    70.12      13.89         0.0  30.48 -115.95

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = weather_df.copy()

hotel_df["Hotel Name"] = ""
hotel_df["Hotel_lat"] = ""
hotel_df["Hotel_lng"] = ""

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "types": "hotel",
    "key": g_key
}
# # use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

     # get city lattitude and longtitude from dataframe
    lat = row['Lat']
    lng = row['Lng']

     # add the Lat and Lng value to the parameter list
    params['location'] = f'{lat},{lng}'

     # assemble url and make API request
    response = requests.get(base_url, params=params).json()
  
    # extract results
    results = response['results']
  
    try:
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        hotel_df.loc[index, 'Hotel_lat'] = results[0]["geometry"]["location"]["lat"]
        hotel_df.loc[index, 'Hotel_lng'] = results[0]["geometry"]["location"]["lng"]
        
        
    except (KeyError, IndexError):
          print("Missing field/result... skipping.")
        

hotel_df.head()

,City,Country,MaxTemp,WindSpeed,Cloudiness,Lat,Lng,Hotel Name,Hotel_lat,Hotel_lng
101,kostek,RU,74.55,10.63,0.0,43.34,46.85,Kostek,43.3432,46.8532
108,guerrero negro,MX,70.92,18.34,0.0,27.98,-114.06,Guerrero Negro,27.9592,-114.057
212,darnah,LY,75.09,13.62,0.0,32.77,22.64,Derna,32.7556,22.6377
434,san quintin,MX,70.12,13.89,0.0,30.48,-115.95,Lázaro Cárdenas,30.5253,-115.933

In [7]:
hotel_df = hotel_df.replace("", np.nan)
hotel_df = hotel_df.dropna()
hotel_df.head()

,City,Country,MaxTemp,WindSpeed,Cloudiness,Lat,Lng,Hotel Name,Hotel_lat,Hotel_lng
101,kostek,RU,74.55,10.63,0.0,43.34,46.85,Kostek,43.3432,46.8532
108,guerrero negro,MX,70.92,18.34,0.0,27.98,-114.06,Guerrero Negro,27.9592,-114.057
212,darnah,LY,75.09,13.62,0.0,32.77,22.64,Derna,32.7556,22.6377
434,san quintin,MX,70.12,13.89,0.0,30.48,-115.95,Lázaro Cárdenas,30.5253,-115.933

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel_lat", "Hotel_lng"]]

In [9]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))